package com.zinios.dealab.model;
// Generated Oct 25, 2018 2:43:44 PM by Hibernate Tools 3.6.0

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Company generated by hbm2java
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class Company implements java.io.Serializable {

	private Long id;
	private String name;
	private String logo;
	private String coverImage;
	private String description;
	private String contact1;
	private String cantact2;
	private Integer status;
	private String website;
	private String hqAddress;


	public Company() {
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLogo() {
		return logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	public String getCoverImage() {
		return coverImage;
	}

	public void setCoverImage(String coverImage) {
		this.coverImage = coverImage;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getContact1() {
		return contact1;
	}

	public void setContact1(String contact1) {
		this.contact1 = contact1;
	}

	public String getCantact2() {
		return cantact2;
	}

	public void setCantact2(String cantact2) {
		this.cantact2 = cantact2;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getWebsite() {
		return website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getHqAddress() {
		return hqAddress;
	}

	public void setHqAddress(String hqAddress) {
		this.hqAddress = hqAddress;
	}
}
